apiVersion: apps/v1
kind: Deployment
metadata:
  name: "portfolio"
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "portfolio"
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: gcr.io/reliable-strata-378620/tesreact:latest

        resources:
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: "portfolio-lb"
  namespace: default

spec:
  selector:
    app: portfolio
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer